spring.application.name=developer
# application.properties
spring.datasource.url=jdbc:mysql://localhost:8080/employee
spring.datasource.username=user1
spring.datasource.password=6281217366
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate properties (optional, but commonly used)
spring.jpa.hibernate.ddl-auto=update # or none, create, create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect